const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const titles={executive:'Executive overview',credit:'Credit & Lending',conflict:'Metric conflict resolution',dictionary:'KPI dictionary',selfservice:'Self-service analytics hub'};
function navigate(id){$$('.view,.nav-item').forEach(x=>x.classList.remove('active'));$(`#${id}`).classList.add('active');$(`.nav-item[data-view="${id}"]`).classList.add('active');$('#page-title').textContent=titles[id];history.replaceState(null,'',`#${id}`);window.scrollTo(0,0)}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
function kpis(items,target){$(target).innerHTML=items.map(k=>`<article class="kpi-card"><div class="kpi-top"><span class="domain">${k.domain}</span><span class="cert-dot" title="Certified">●</span></div><h3>${k.value}</h3><p>${k.name}<span class="change ${k.tone}">${k.change}</span></p><p>${k.note}</p></article>`).join('')}
function lineChart(target,series,months,colors){const w=700,h=220,p=30,vals=series.flatMap(s=>s.values),max=Math.max(...vals)*1.1,min=0;let svg=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">`;for(let i=0;i<5;i++){let y=p+i*(h-2*p)/4;svg+=`<line class="grid-line" x1="${p}" y1="${y}" x2="${w-p}" y2="${y}"/>`}series.forEach((s,si)=>{const pts=s.values.map((v,i)=>`${p+i*(w-2*p)/(s.values.length-1)},${h-p-(v-min)/(max-min)*(h-2*p)}`).join(' ');svg+=`<polyline class="series-line" stroke="${colors[si]}" points="${pts}"/>`});months.forEach((m,i)=>{if(i%2===0||i===months.length-1)svg+=`<text class="axis-label" text-anchor="middle" x="${p+i*(w-2*p)/(months.length-1)}" y="${h-6}">${m}</text>`});svg+='</svg>';$(target).innerHTML=svg}
function renderTrends(period=12){const start=12-period,months=BI_DATA.months.slice(start);lineChart('#revenue-chart',[{values:BI_DATA.monthly.netRevenue.slice(start)},{values:BI_DATA.monthly.paymentVolume.slice(start).map(x=>x/20)}],months,['#246bfd','#20c997']);lineChart('#dpd-chart',[{values:BI_DATA.monthly.dpd30.slice(start)}],months,['#f58a4b'])}
function render(){kpis(BI_DATA.execKpis,'#kpi-grid');kpis([{name:'Applications',value:'24,500',change:'+8.2%',tone:'up',domain:'Origination',note:'Unique submitted'},{name:'Approval rate',value:'42.5%',change:'+1.3 pp',tone:'up',domain:'Decisioning',note:'Approved / eligible'},{name:'Loan book',value:'AED 386M',change:'+4.7%',tone:'up',domain:'Portfolio',note:'Principal outstanding'},{name:'30+ DPD',value:'2.8%',change:'0.0 pp',tone:'flat',domain:'Risk',note:'Limit ≤ 3.0%'}],'#credit-kpis');
  renderTrends();
  const total=BI_DATA.customerMix.reduce((a,b)=>a+b.value,0),stops=[];let acc=0;BI_DATA.customerMix.forEach(x=>{let start=acc/total*360;acc+=x.value;stops.push(`${x.color} ${start}deg ${acc/total*360}deg`)});$('#mix-chart').innerHTML=`<div class="donut-layout"><div class="donut" style="background:conic-gradient(${stops.join(',')})"><div class="donut-center"><b>128.4K</b><small>customers</small></div></div><div class="mix-legend">${BI_DATA.customerMix.map(x=>`<div><i style="background:${x.color}"></i><span>${x.label}</span><b>${Math.round(x.value/total*100)}%</b></div>`).join('')}</div></div>`;
  const funnelHtml=BI_DATA.funnel.map(x=>`<div class="funnel-row"><span>${x.label}</span><div class="bar-track"><div class="bar" style="width:${x.value/BI_DATA.funnel[0].value*100}%"></div></div><b>${x.value.toLocaleString()}</b></div>`).join('');$('#mini-funnel').innerHTML=funnelHtml;$('#credit-funnel').innerHTML=funnelHtml;
  $('#alerts').innerHTML='<div class="alert"><span class="alert-icon">!</span><div><strong>NTB risk is nearing limit</strong><small>30+ DPD at 2.8%; 0.2 pp headroom.</small></div></div><div class="alert good"><span class="alert-icon">✓</span><div><strong>Revenue ahead of run-rate</strong><small>September net revenue grew 5.8% MoM.</small></div></div><div class="alert good"><span class="alert-icon">↗</span><div><strong>Payment engagement rising</strong><small>TPV grew faster than active customers.</small></div></div>';
  const qTotal=BI_DATA.quality.reduce((a,b)=>a+b.value,0);$('#quality-chart').innerHTML=`<div style="display:flex;height:38px;border-radius:7px;overflow:hidden;margin:45px 0 25px">${BI_DATA.quality.map(x=>`<div title="${x.label}: AED ${x.value}M" style="width:${x.value/qTotal*100}%;background:${x.color}"></div>`).join('')}</div>${BI_DATA.quality.map(x=>`<div style="display:flex;justify-content:space-between;margin:11px 0;font-size:12px"><span><i style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${x.color};margin-right:7px"></i>${x.label}</span><b>AED ${x.value}M · ${(x.value/qTotal*100).toFixed(1)}%</b></div>`).join('')}`;
  $('#definition-cards').innerHTML=BI_DATA.definitions.map(x=>`<article class="card definition"><span class="team">${x.team} definition</span><h3>${x.value}</h3><span class="delta">${x.delta} vs certified</span><h4>${x.label}</h4><p>${x.text}</p><footer><span>${x.status}</span><span>Exploratory</span></footer></article>`).join('');renderDictionary();}
function renderDictionary(){const q=$('#metric-search').value.toLowerCase(),d=$('#domain-filter').value,s=$('#status-filter').value;const rows=BI_DATA.metrics.filter(m=>(d==='all'||m[1]===d)&&(s==='all'||m[6]===s)&&m.join(' ').toLowerCase().includes(q));$('#dictionary-body').innerHTML=rows.map(m=>`<tr>${m.slice(0,6).map(x=>`<td>${x}</td>`).join('')}<td><span class="status-pill ${m[6]}">${m[6]}</span></td></tr>`).join('');$('#metric-count').textContent=`${rows.length} of ${BI_DATA.metrics.length} metrics`}
['#metric-search','#domain-filter','#status-filter'].forEach(s=>$(s).addEventListener('input',renderDictionary));
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2300)}
$('#request-access').onclick=()=>{navigator.clipboard?.writeText('Dataset requested:\nBusiness purpose:\nRequired fields:\nRequired until:\nManager:\n');toast('Access-request template copied')};
$('#export-btn').onclick=()=>{const rows=[['Metric','Value','Change','Domain'],...BI_DATA.execKpis.map(k=>[k.name,k.value,k.change,k.domain])];const blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mal-executive-kpis-sep-2026.csv';a.click();URL.revokeObjectURL(a.href);toast('Executive KPI export downloaded')};
$('#period').onchange=e=>{renderTrends(Number(e.target.value));toast(`View updated: last ${e.target.value} months`)};
render();const initial=location.hash.slice(1);if(titles[initial])navigate(initial);
